# Documentation: http//docs.travis-ci.com/user/language/julia/
language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
matrix:
    allow_failures:
        - julia: 0.7
        - julia: 1.0
        - julia: nightly
notifications:
email: false
