# Documentation: http//docs.travis-ci.com/user/language/julia/
language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
git:
    depth: 999999
matrix:
    allow_failures:
        - julia: nightly
compiler:
    - clang
    - gcc
notifications:
    email: false
