# Documentation: http//docs.travis-ci.com/user/language/julia/
language: julia
dist: trusty
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
matrix:
    allow_failures:
        - julia: 0.7
        - julia: 1.0
        - julia: nightly
notifications:
    email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
