# Documentation: http//docs.travis-ci.com/user/language/julia/
language: julia
install: make get-deps
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
matrix:
    allow_failures:
        - julia: nightly
compiler:
    - clang
      - gcc
notifications:
    email: false
